### ISSUE TITLE
Better legibility: custom font size & improved line height

### ISSUE THREAD

**Issue by garrett** [GeopJr/Tooth#40]
Thanks for picking up Tootle. Tooth looks great so far!

It's often hard to read lots of text on the screen, as I need to wear glasses due to nearsightedness and astigmatism. Reading fonts at a smaller size is especially difficult in messages and documents. Default UI text is usually OK, but reading more than a bit is harder, so I often crank up document text sizes. (Note: Changing global font size on GNOME is overkill, as I don't need _all_ text and UI to be larger.)

Could Tooth support larger fonts for posts? And possibly adjust the line-height too (it feels a little too tight at the moment)?

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It should be fixed as of 0c2876861f314b9611ac35378291fae313f1a168.

It should be in settings under "Status".
(I also pushed keyboard navigation since I've been sitting on it for a while)

Feel free to re-open this issue if the large font size or line height do not feel right!
