### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tooth#6]
For the sake of not conflicting with Tootle, in case it gets unarchived in the future, I went ahead and rebranded this fork.

The name I went with is **Toot**h. Another idea was Tooter (but it seems to already be an app/social media platform).

The current logo is Tootle's but in a blue accent (similar to Chromium). Since the name is Tooth, a new logo is needed (probably designed after a... tooth).

**Comment by Pottit** [comment]
Since it's a mastodon app called tooth, maybe a tusk-based logo could work. I know they're not technically teeth, but still..

Made a rough proof of concept. Not sure if it works, might not be recognizable enough at all. (Also I'm not at all a designer, so I couldn't ever cook up anything actually good)

![tusk logo](https://user-images.githubusercontent.com/66686459/204927665-01430d8f-46b8-4f03-b156-d75fba3f38b3.svg)

**Comment by GeopJr** [comment]
That's a nice idea!

My main concern is how would tusks be designed to fit the [GNOME HIG on icons](https://developer.gnome.org/hig/guidelines/app-icons.html). When I originally made the issue, tusks hadn't even crossed my mind - I was imagining a human tooth (which would easily fit in a rectangular or square icon shape from the HIG). Tusks definitely fit the Mastodon theme better!

**Comment by j-mizzle** [comment]
This looks way to similar to the icon for Tusky (Android fedi client)

**Comment by spaetz** [comment]
How about the head of a sabretooth tiger (public domain version of tiger is here) https://openclipart.org/detail/218801/diego

I am no artist or I would prepare some draft :)
